name: Versioning

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  calculate-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitVersion 6.x
        run: |
          dotnet tool install --global GitVersion.Tool --version 6.*

      - name: Run GitVersion 6.x
        id: gitversion
        run: |
          VERSION=$( dotnet-gitversion /output json )

      - name: Show all GitVersion outputs
        run: |
          echo "FullSemVer: $(echo $VERSION | jq -r '.FullSemVer')"
          echo "Major: $(echo $VERSION | jq -r '.Major')"
          echo "Minor: $(echo $VERSION | jq -r '.Minor')"
          echo "Patch: $(echo $VERSION | jq -r '.Patch')"
