name: Versioning

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  calculate-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitVersion 6.x
        run: |
          dotnet tool install --global GitVersion.Tool --version 6.*

      - name: Run GitVersion 6.x
        id: gitversion
        run: |
          echo "VERSION=$(gitversion /output json | jq -r '.FullSemVer')" >> $GITHUB_ENV

      - name: Show all GitVersion outputs
        run: |
          echo "FullSemVer: ${{ steps.gitversion.outputs.FullSemVer }}"
          echo "Major: ${{ steps.gitversion.outputs.Major }}"
          echo "Minor: ${{ steps.gitversion.outputs.Minor }}"
          echo "Patch: ${{ steps.gitversion.outputs.Patch }}"
          echo "PreReleaseTag: ${{ steps.gitversion.outputs.PreReleaseTag }}"
          echo "PreReleaseNumber: ${{ steps.gitversion.outputs.PreReleaseNumber }}"
          echo "BuildMetaData: ${{ steps.gitversion.outputs.BuildMetaData }}"
          echo "Sha: ${{ steps.gitversion.outputs.Sha }}"
          echo "ShortSha: ${{ steps.gitversion.outputs.ShortSha }}"
          echo "BranchName: ${{ steps.gitversion.outputs.BranchName }}"
          echo "CommitDate: ${{ steps.gitversion.outputs.CommitDate }}"
