name: Versioning

on:
  push:
  pull_request:
  workflow_dispatch:


jobs:
  calculate-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitVersion 6.x
        run: |
          dotnet tool install --global GitVersion.Tool --version 6.*

      - name: Run GitVersion 6.x
        id: gitversion
        run: |
          echo "FULLSEMVER=$( dotnet-gitversion /output json | jq -r '.FullSemVer')" >> $GITHUB_ENV

      - name: Show all GitVersion outputs
        run: |
          echo "FullSemVer: $FULLSEMVER"
